### ISSUE TITLE
Runtimeconfig Autogen Configuration Files

### ISSUE THREAD

**Issue by chemelnucfin** [googleapis/python-runtimeconfig#2]
According to discussions in issues googleapis/google-cloud-python#3897 and googleapis/google-cloud-python#3898 and PR googleapis/google-cloud-python#4810, it is probably more desirable to use the autogen to set up the client library and resolve the issue of not being able to connect to the api in googleapis/google-cloud-python#3897 and missing text access in googleapis/google-cloud-python#3898 instead of resolving the issues manually.  

The other issues will be closed in favor of this, which should resolve both issues together.

**Comment by parthea** [comment]
We have an internal goal to increase the number of autogenerated clients, this includes migrating manual clients. We're tracking manual clients through a configuration in the .repo-metadata.json here https://github.com/googleapis/python-runtimeconfig/blob/master/.repo-metadata.json#L9 .
